version: '3'

networks:
  example:
services:
  web:
    image: webdevops/php-nginx:8.0
    container_name: web
    links:
      - db
    ports:
      - "8080:80"
    volumes:
      - ./src:/app
    depends_on:
      - db
    environment:
      WEB_DOCUMENT_ROOT: /app/public
    networks:
      - example
  db:
    image: mysql:5.7.39
    container_name: db
    restart: unless-stopped
    tty: true
    ports:
      - "4306:3306"
    volumes:
      - ./config/mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ukf-events
      MYSQL_USER: laravel
      MYSQL_PASSWORD: test
      MYSQL_ROOT_PASSWORD: test
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - example
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    links:
      - db
    ports:
      - "8181:80"
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: test
    networks:
      - example