version: '3'

networks:
  example:
services:
  php-nginx:
    image: webdevops/php-nginx:8.0
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./src:/app
    depends_on:
      - mysql
    networks:
      - example
  mysql:
    image: mysql:5.7.30
    container_name: MySQLDatabase
    restart: unless-stopped
    tty: true
    ports:
      - "4306:3306"
    volumes:
      - ./config/mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: test
      MYSQL_ROOT_PASSWORD: test
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - example